### ISSUE TITLE
Admin view: sorting on all columns

### ISSUE THREAD

**Issue by blueyed** [catcombo/django-speedinfo#5]
While not (easily) directly supported in the DB, ordering of calculated fields could be also provided.

This would allow to sort on e.g. "SQL time" also.

Do you think this is useful?

**Comment by catcombo** [comment]
I think adding the missing sort won't be a big problem and can be useful for someone. At least to you, if you ask about it :) I'll try to do this feature till the end of the week.

**Comment by catcombo** [comment]
Sorting added in [v1.3.7](https://github.com/catcombo/django-speedinfo/releases/tag/v1.3.7)
