### ISSUE TITLE
Adding custom fields in admin panel?

### ISSUE THREAD

**Issue by ChillarAnand** [catcombo/django-speedinfo#9]
What options are available for users if they have to add custom fields in the admin? For example, the percentile of total time.

One option is users can register the model by themselves. speedinfo has to ignore the registration if the model is already registered.

**Comment by catcombo** [comment]
Add custom field name to `SPEEDINFO_REPORT_COLUMNS` and how the field should be calculated and formatted to `SPEEDINFO_REPORT_COLUMNS_FORMAT`. You can see an example of how this can be done in the [speedinfo/settings.py](https://github.com/catcombo/django-speedinfo/blob/master/speedinfo/settings.py#L16) and how this settings are used in [speedinfo/admin.py](https://github.com/catcombo/django-speedinfo/blob/master/speedinfo/admin.py#L68).

**Comment by ChillarAnand** [comment]
Thanks. @catcombo
